export enum ErrorCode {
  PRODUCT_NOT_FOUND= "PRODUCT_NOT_FOUND",
  DB_ERROR = "DB_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  USER_NOT_EXIST = "USER_NOT_EXIST",
  PASSWORD_INCORRECT = "PASSWORD_INCORRECT",
}
