export enum ErrorCode {
  DB_ERROR = "DB_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  USER_NOT_EXIST = "USER_NOT_EXIST",
  PASSWORD_INCORRECT = "PASSWORD_INCORRECT",
  NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  NOT_ADMIN = "NOT_ADMIN",
}
